# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\etherousUI.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from generator import generator


class Ui_mainFrame(object):

    def setupUi(self, mainFrame):
        mainFrame.setObjectName("mainFrame")
        mainFrame.resize(1386, 1457)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainFrame.sizePolicy().hasHeightForWidth())
        mainFrame.setSizePolicy(sizePolicy)
        mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.generateBtn = QtWidgets.QPushButton(mainFrame)
        self.generateBtn.setGeometry(QtCore.QRect(570, 1300, 225, 69))
        self.generateBtn.setObjectName("generateBtn")
        self.generateBtn.clicked.connect(self.buttonClick)

        self.line = QtWidgets.QFrame(mainFrame)
        self.line.setGeometry(QtCore.QRect(650, 0, 71, 841))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(mainFrame)
        self.line_2.setGeometry(QtCore.QRect(0, 830, 1381, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lineEdit_7 = QtWidgets.QLineEdit(mainFrame)
        self.lineEdit_7.setGeometry(QtCore.QRect(1510, 500, 71, 45))
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_16 = QtWidgets.QLabel(mainFrame)
        self.label_16.setGeometry(QtCore.QRect(1420, 500, 138, 39))
        self.label_16.setObjectName("label_16")
        self.line_3 = QtWidgets.QFrame(mainFrame)
        self.line_3.setGeometry(QtCore.QRect(0, 1220, 1381, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formLayoutWidget = QtWidgets.QWidget(mainFrame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 651, 741))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.fromInfo = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.fromInfo.setContentsMargins(0, 0, 0, 0)
        self.fromInfo.setObjectName("fromInfo")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.fromInfo.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fromFirstNamelabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.fromFirstNamelabel.setObjectName("fromFirstNamelabel")
        self.fromInfo.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fromFirstNamelabel)
        self.fromFirstName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fromFirstName.setObjectName("fromFirstName")
        self.fromInfo.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fromFirstName)
        self.fromLastNamelabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.fromLastNamelabel.setObjectName("fromLastNamelabel")
        self.fromInfo.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fromLastNamelabel)
        self.fromLastName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fromLastName.setObjectName("fromLastName")
        self.fromInfo.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fromLastName)
        self.midNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.midNameLabel.setObjectName("midNameLabel")
        self.fromInfo.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.midNameLabel)
        self.fromMidName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fromMidName.setObjectName("fromMidName")
        self.fromInfo.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fromMidName)
        self.addressLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.addressLabel.setObjectName("addressLabel")
        self.fromInfo.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.addressLabel)
        self.fromStreet = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fromStreet.setObjectName("fromStreet")
        self.fromInfo.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fromStreet)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.fromInfo.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.fromCity = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fromCity.setText("")
        self.fromCity.setObjectName("fromCity")
        self.fromInfo.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.fromCity)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.fromInfo.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.fromState = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fromState.setText("")
        self.fromState.setObjectName("fromState")
        self.fromInfo.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.fromState)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.fromInfo.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.fromCountry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fromCountry.setText("")
        self.fromCountry.setObjectName("fromCountry")
        self.fromInfo.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.fromCountry)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.fromInfo.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.fromZipcode = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fromZipcode.setText("")
        self.fromZipcode.setObjectName("fromZipcode")
        self.fromInfo.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.fromZipcode)
        self.fromEmailLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.fromEmailLabel.setObjectName("fromEmailLabel")
        self.fromInfo.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.fromEmailLabel)
        self.fromEmail = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fromEmail.setText("")
        self.fromEmail.setObjectName("fromEmail")
        self.fromInfo.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.fromEmail)
        self.fromEmailLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.fromEmailLabel_2.setObjectName("fromEmailLabel_2")
        self.fromInfo.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.fromEmailLabel_2)
        self.fromPhone = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fromPhone.setText("")
        self.fromPhone.setObjectName("fromPhone")
        self.fromInfo.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.fromPhone)
        self.formLayoutWidget_2 = QtWidgets.QWidget(mainFrame)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(690, 20, 661, 741))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.toInfo = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.toInfo.setContentsMargins(0, 0, 0, 0)
        self.toInfo.setObjectName("toInfo")
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.toInfo.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.toInfo.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.toFirstName = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.toFirstName.setObjectName("toFirstName")
        self.toInfo.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.toFirstName)
        self.toLastName = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.toLastName.setObjectName("toLastName")
        self.toInfo.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.toLastName)
        self.toMiddleName = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.toMiddleName.setObjectName("toMiddleName")
        self.toInfo.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.toMiddleName)
        self.toStreet = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.toStreet.setObjectName("toStreet")
        self.toInfo.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.toStreet)
        self.toCity = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.toCity.setText("")
        self.toCity.setObjectName("toCity")
        self.toInfo.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.toCity)
        self.toState = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.toState.setText("")
        self.toState.setObjectName("toState")
        self.toInfo.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.toState)
        self.toCountry = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.toCountry.setText("")
        self.toCountry.setObjectName("toCountry")
        self.toInfo.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.toCountry)
        self.toZipcode = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.toZipcode.setText("")
        self.toZipcode.setObjectName("toZipcode")
        self.toInfo.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.toZipcode)
        self.toEmail = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.toEmail.setText("")
        self.toEmail.setObjectName("toEmail")
        self.toInfo.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.toEmail)
        self.toPhone = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.toPhone.setText("")
        self.toPhone.setObjectName("toPhone")
        self.toInfo.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.toPhone)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.toInfo.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.toInfo.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.toInfo.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.toInfo.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.toInfo.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.toInfo.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.toInfo.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.toEmailLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.toEmailLabel.setObjectName("toEmailLabel")
        self.toInfo.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.toEmailLabel)
        self.fromEmailLabel_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.fromEmailLabel_3.setObjectName("fromEmailLabel_3")
        self.toInfo.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.fromEmailLabel_3)
        self.label_3 = QtWidgets.QLabel(mainFrame)
        self.label_3.setGeometry(QtCore.QRect(10, 820, 158, 78))
        self.label_3.setObjectName("label_3")
        self.formLayoutWidget_3 = QtWidgets.QWidget(mainFrame)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(120, 850, 333, 362))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.width = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.width.setObjectName("width")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.width)
        self.length = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.length.setText("")
        self.length.setObjectName("length")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.length)
        self.weight = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.weight.setObjectName("weight")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.weight)
        self.distanceUnit = QtWidgets.QComboBox()
        self.distanceUnit.setObjectName("unit")
        self.distanceUnit.addItem("Inch")
        self.distanceUnit.addItem("CM")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.distanceUnit)
        self.height = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.height.setObjectName("height")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.height)

        self.retranslateui(mainFrame)
        QtCore.QMetaObject.connectSlotsByName(mainFrame)

    def retranslateui(self, mainFrame):
        _translate = QtCore.QCoreApplication.translate
        mainFrame.setWindowTitle(_translate("mainFrame", "Frame"))
        self.generateBtn.setText(_translate("mainFrame", "Generate"))
        self.label_16.setText(_translate("mainFrame", "State"))
        self.label_2.setText(_translate("mainFrame", "From:"))
        self.fromFirstNamelabel.setText(_translate("mainFrame", "First Name *"))
        self.fromLastNamelabel.setText(_translate("mainFrame", "Last Name *"))
        self.midNameLabel.setText(_translate("mainFrame", "Mid "))
        self.addressLabel.setText(_translate("mainFrame", "Address *"))
        self.label_6.setText(_translate("mainFrame", "City*"))
        self.label_7.setText(_translate("mainFrame", "State"))
        self.label_8.setText(_translate("mainFrame", "Counrty *"))
        self.label_9.setText(_translate("mainFrame", "Zip Code *"))
        self.fromEmailLabel.setText(_translate("mainFrame", "Email  *"))
        self.fromEmailLabel_2.setText(_translate("mainFrame", "Phone  *"))
        self.label_18.setText(_translate("mainFrame", "To:"))
        self.label_10.setText(_translate("mainFrame", "First Name *"))
        self.label_17.setText(_translate("mainFrame", "Last Name *"))
        self.label_13.setText(_translate("mainFrame", "Mid"))
        self.label_11.setText(_translate("mainFrame", "Address*"))
        self.label_12.setText(_translate("mainFrame", "City*"))
        self.label_19.setText(_translate("mainFrame", "State"))
        self.label_15.setText(_translate("mainFrame", "Counrty*"))
        self.label_14.setText(_translate("mainFrame", "Zip Code*"))
        self.toEmailLabel.setText(_translate("mainFrame", "Email  *"))
        self.fromEmailLabel_3.setText(_translate("mainFrame", "Phone  *"))
        self.label_3.setText(_translate("mainFrame", "Parcel"))
        self.label_4.setText(_translate("mainFrame", "Width"))
        self.label_20.setText(_translate("mainFrame", "Length"))
        self.label_22.setText(_translate("mainFrame", "weight"))
        self.label_21.setText(_translate("mainFrame", "distanceUnit"))
        self.label_23.setText(_translate("mainFrame", "mass(lb)"))
        self.label_5.setText(_translate("mainFrame", "Height"))

    def buttonClick(self):
        if self.check() == False:
            msg = QMessageBox()
            msg.setText("Some info has not been filled!")
            msg.exec()
        else:
            self.convert()
            print("now generating")
            w = generator(self.name1, self.street1, self.city1, self.state1, self.country1, self.zipcode1, self.email1,
                          self.phone1,self.name2, self.street2, self.city2, self.state2, self.country2, self.zipcode2,
                         self.email2,self.phone2,self.parwidth,self.parlength,self.parweight,self.distance_unit,self.parheight)
            w.construct()
            w.generating()

    def convert(self):
        self.name1 = str(self.fromFirstName.text() + self.fromLastName.text())
        self.street1 = str(self.fromStreet.text())
        self.city1 = str(self.fromCity.text())
        self.state1 = str(self.fromState.text())
        self.country1 = str(self.fromCountry.text())
        self.zipcode1 = str(self.fromZipcode.text())
        self.email1 = str(self.fromEmail.text())
        self.phone1 = str(self.fromPhone.text())

        self.name2 = str(self.toFirstName.text() + self.toLastName.text())
        self.street2 = str(self.toStreet.text())
        self.city2 = str(self.toCity.text())
        self.state2 = str(self.toState.text())
        self.country2 = str(self.toCountry.text())
        self.zipcode2 = str(self.toZipcode.text())
        self.email2 = str(self.toEmail.text())
        self.phone2 = str(self.toPhone.text())

        self.parwidth = str(self.width.text())
        self.parlength = str(self.length.text())
        self.parweight = str(self.weight.text())
        self.distance_unit = str(self.distanceUnit.currentText())
        self.parheight = str(self.height.text())

    def check(self):
        if self.fromFirstName.text() == "" or self.fromLastName.text() == "" or self.fromStreet == "" \
                or self.fromCity.text() == "" or self.fromState.text() == "" or self.fromCountry.text() == "" \
                or self.fromZipcode.text() == "" or self.fromEmail.text() == "" or self.fromPhone.text() == "" \
                or self.toFirstName.text() == "" or self.toLastName.text() == "" or self.toStreet == "" \
                or self.toCity.text() == "" or self.toState.text() == "" or self.toCountry.text() == "" \
                or self.toZipcode.text() == "" or self.toEmail.text() == "" or self.toPhone.text() == "" \
                or self.width.text() == "" or self.length.text() == "" or self.weight.text() == "" \
                or self.height.text() == "":
            return False
        else:
            print("Hello")
            return True


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    mainFrame = QtWidgets.QFrame()
    ui = Ui_mainFrame()
    ui.setupUi(mainFrame)
    mainFrame.show()
    sys.exit(app.exec_())
